### ISSUE TITLE
remove R dependency

### ISSUE THREAD

**Issue by mgiraldo** [NYPL/map-vectorizer#21]
I originally used R because I found code that reduces the amount of corners in a geographic polygon: http://rpubs.com/geospacedman/alphasimple

The function in the vectorizer is:
https://github.com/NYPL/map-vectorizer/blob/9b9129b9d135c89b350700549794e7d0f2348af2/vectorize_map.py#L227

and the R code:
https://github.com/NYPL/map-vectorizer/blob/9b9129b9d135c89b350700549794e7d0f2348af2/simplify_map.R

Ideally, we would eliminate R and have python code that produces the same output as R (one shapefile for each polygon that was simplified that is within the area threshold).

A shapefile-per-polygon is produced (thousands!) because it was the only way I could pass data from python-to-R-and-back but was also useful to find the average color of the polygon.

**Comment by tlevine** [comment]
Is this a duplicate of issue #12?

Also, you only needed shapefiles to communicate between R and Python; the shapes can stay in memory if it's just Python.

**Comment by mgiraldo** [comment]
correct
