### ISSUE TITLE
I am on Windows. Is it possible to run this project on Windows?

### ISSUE THREAD

**Issue by ShuaiW** [NYPL/map-vectorizer#25]
I am on Windows. Is it possible to run this project on Windows?

**Comment by mgiraldo** [comment]
I have not tested any of this on Windows. it is probably possible to run it but I imagine a lot of customization would need to happen, like folder behavior (Windows uses backslashes) and similar things. I'm sorry I can't be of much help since I don't have a Windows machine to test this on.

**Comment by ShuaiW** [comment]
Thanks for your reply.  I am testing it on a Mac now and got a "Could not open shapefile" error

inside-65-56-205:map-vectorizer shuaiwang$ python vectorize_map.py test.tif


```



NYPL Labs Map Vectorizer v0.1 
=============================
By: Mauricio Giraldo Arteaga @mgiraldo / @nypl_labs

GIMP executable path [/Applications/Gimp.app/Contents/MacOS/gimp-2.8]: 


Processing file: test.tif



Thresholdizing:
---------------
test.tif into threshold file: test/test-threshold-tmp.tif
sh: /Applications/Gimp.app/Contents/MacOS/gimp-2.8: No such file or directory


Geodata obtained:
-----------------
W -73.9968041
N 40.7219642
E -73.9955339
S 40.7205240


Applying to destination:
------------------------
ERROR 4: `test/test-threshold-tmp.tif' does not exist in the file system,
and is not recognised as a supported dataset name.

GDALOpen failed - 4
`test/test-threshold-tmp.tif' does not exist in the file system,
and is not recognised as a supported dataset name.


ERROR 4: `test/test-wsg-tmp.tif' does not exist in the file system,
and is not recognised as a supported dataset name.


Polygonizing (coarse):
----------------------
ERROR 4: `test/test-gdal-tmp.tif' does not exist in the file system,
and is not recognised as a supported dataset name.

Unable to open test/test-gdal-tmp.tif

Splitting megapolygon file into chunks
--------------------------------------
Could not open shapefile

```

**Comment by mgiraldo** [comment]
there's a `sh: /Applications/Gimp.app/Contents/MacOS/gimp-2.8: No such file or directory` right after executing the command... this means the app is not able to find Gimp. it is probably installed in another folder or is another version (other than 2.8). you are asked to either leave the default folder (`/Applications/Gimp.app/Contents/MacOS/gimp-2.8`) or provide your own.

try changing that and see if it works

**Comment by ShuaiW** [comment]
Finally got it work. Thanks a lot
